//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pr1_vnedrenit.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Istoriya_reytinga_parnterov
    {
        public int id_istoriya { get; set; }
        public Nullable<int> id_partnera { get; set; }
        public string stariy_reyting { get; set; }
        public string novy_reyming { get; set; }
        public string data_izminenia { get; set; }
        public Nullable<int> id_manager { get; set; }
    
        public virtual Partneri Partneri { get; set; }
    }
}
