//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pr1_vnedrenit.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materiali
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Materiali()
        {
            this.materiali_dla_proizvodstva = new HashSet<materiali_dla_proizvodstva>();
            this.Sklad = new HashSet<Sklad>();
        }
    
        public int Id_materials { get; set; }
        public Nullable<int> id_tip_matreial { get; set; }
        public string name { get; set; }
        public Nullable<int> id_postavchik { get; set; }
        public Nullable<int> kolichestvo_v_upakovke { get; set; }
        public string edinisa_izmerenie { get; set; }
        public string opisanie { get; set; }
        public string image { get; set; }
        public Nullable<double> stoimost { get; set; }
        public Nullable<int> ostatok { get; set; }
        public Nullable<int> minimalmiy_dopistmiy_zakaz { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<materiali_dla_proizvodstva> materiali_dla_proizvodstva { get; set; }
        public virtual Postavchiki Postavchiki { get; set; }
        public virtual tip_materiala tip_materiala { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sklad> Sklad { get; set; }
    }
}
