//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pr1_vnedrenit.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class materiali_dla_proizvodstva
    {
        public int id_material_dla_proizvodstvA { get; set; }
        public Nullable<int> id_material { get; set; }
        public int id_productsi { get; set; }
        public Nullable<int> kolischetvo { get; set; }
    
        public virtual Materiali Materiali { get; set; }
        public virtual Productsia Productsia { get; set; }
    }
}
