//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pr1_vnedrenit.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class pr1_vnedrenieEntities : DbContext
    {
        public pr1_vnedrenieEntities()
            : base("name=pr1_vnedrenieEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        private static pr1_vnedrenieEntities entities;

        public static pr1_vnedrenieEntities GetContext() {

            if (entities==null)
            {
                return entities = new pr1_vnedrenieEntities();

            }
            return entities;
        
        }
    
        public virtual DbSet<Id_tip_partnera> Id_tip_partnera { get; set; }
        public virtual DbSet<Istoriya_reytinga_parnterov> Istoriya_reytinga_parnterov { get; set; }
        public virtual DbSet<Materiali> Materiali { get; set; }
        public virtual DbSet<materiali_dla_proizvodstva> materiali_dla_proizvodstva { get; set; }
        public virtual DbSet<Menedcher> Menedcher { get; set; }
        public virtual DbSet<Partneri> Partneri { get; set; }
        public virtual DbSet<Postavchiki> Postavchiki { get; set; }
        public virtual DbSet<Productsia> Productsia { get; set; }
        public virtual DbSet<Secha> Secha { get; set; }
        public virtual DbSet<Sklad> Sklad { get; set; }
        public virtual DbSet<Skladskie_operatsi> Skladskie_operatsi { get; set; }
        public virtual DbSet<Sotrudniki> Sotrudniki { get; set; }
        public virtual DbSet<Status_zayavki> Status_zayavki { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tip_materiala> tip_materiala { get; set; }
        public virtual DbSet<tip_productsi> tip_productsi { get; set; }
        public virtual DbSet<Zayavka> Zayavka { get; set; }
    }
}
