//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pr1_vnedrenit.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partneri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Partneri()
        {
            this.Istoriya_reytinga_parnterov = new HashSet<Istoriya_reytinga_parnterov>();
            this.Zayavka = new HashSet<Zayavka>();
        }
    
        public int Id_partner { get; set; }
        public Nullable<int> Id_tip_partnera { get; set; }
        public string naimenovanie_company { get; set; }
        public string yuridichestkiy_adres { get; set; }
        public string INN { get; set; }
        public string fio_directora { get; set; }
        public string email { get; set; }
        public string kontaktnie_dannie { get; set; }
        public string reyting { get; set; }
        public string logotip { get; set; }
        public string mesta_prodachi { get; set; }
        public string obchiy_obyom_prodaz { get; set; }
    
        public virtual Id_tip_partnera Id_tip_partnera1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Istoriya_reytinga_parnterov> Istoriya_reytinga_parnterov { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zayavka> Zayavka { get; set; }
    }
}
