//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pr1_vnedrenit.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Postavchiki
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Postavchiki()
        {
            this.Materiali = new HashSet<Materiali>();
        }
    
        public int id_postavchic { get; set; }
        public Nullable<int> id_tip_postavhiki { get; set; }
        public string naimenovanie { get; set; }
        public string INN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Materiali> Materiali { get; set; }
    }
}
