//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pr1_vnedrenit.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productsia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Productsia()
        {
            this.materiali_dla_proizvodstva = new HashSet<materiali_dla_proizvodstva>();
            this.Zayavka = new HashSet<Zayavka>();
        }
    
        public int id_productsia { get; set; }
        public int id_tip_productsi { get; set; }
        public string naimenovanie { get; set; }
        public string artikle { get; set; }
        public string minimaknaya_stoimost_partnera { get; set; }
        public string tip { get; set; }
        public string opisanie { get; set; }
        public string izobrazhenie { get; set; }
        public Nullable<double> razmer_upakovki { get; set; }
        public Nullable<int> ves { get; set; }
        public string sertificat_kachestvo { get; set; }
        public Nullable<System.DateTime> vremya_izgotovlenie { get; set; }
        public string sebestpoimosst { get; set; }
        public Nullable<int> id_secha { get; set; }
        public string kolichestvo_chekov { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<materiali_dla_proizvodstva> materiali_dla_proizvodstva { get; set; }
        public virtual Secha Secha { get; set; }
        public virtual tip_productsi tip_productsi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zayavka> Zayavka { get; set; }
    }
}
