//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pr1_vnedrenit.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sklad
    {
        public int id_sklad { get; set; }
        public Nullable<int> id_materials { get; set; }
        public Nullable<int> id_operatsii { get; set; }
        public Nullable<int> kolischetvo { get; set; }
        public Nullable<System.DateTime> data { get; set; }
    
        public virtual Materiali Materiali { get; set; }
        public virtual Skladskie_operatsi Skladskie_operatsi { get; set; }
    }
}
