//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pr1_vnedrenit.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tip_materiala
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tip_materiala()
        {
            this.Materiali = new HashSet<Materiali>();
        }
    
        public int Id_tip_materiala { get; set; }
        public string tip_materiala1 { get; set; }
        public string procent_braka { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Materiali> Materiali { get; set; }
    }
}
